// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: internal/proto/keeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Number string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Date   string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Code   string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *AddCardRequest) Reset() {
	*x = AddCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCardRequest) ProtoMessage() {}

func (x *AddCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCardRequest.ProtoReflect.Descriptor instead.
func (*AddCardRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{0}
}

func (x *AddCardRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AddCardRequest) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *AddCardRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AddCardRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AddCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddCardResponse) Reset() {
	*x = AddCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCardResponse) ProtoMessage() {}

func (x *AddCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCardResponse.ProtoReflect.Descriptor instead.
func (*AddCardResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{1}
}

type AddLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Login  string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Pwd    string `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *AddLoginRequest) Reset() {
	*x = AddLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLoginRequest) ProtoMessage() {}

func (x *AddLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLoginRequest.ProtoReflect.Descriptor instead.
func (*AddLoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{2}
}

func (x *AddLoginRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AddLoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AddLoginRequest) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type AddLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddLoginResponse) Reset() {
	*x = AddLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLoginResponse) ProtoMessage() {}

func (x *AddLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLoginResponse.ProtoReflect.Descriptor instead.
func (*AddLoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{3}
}

type AddBinaryDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Data   string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddBinaryDataRequest) Reset() {
	*x = AddBinaryDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBinaryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBinaryDataRequest) ProtoMessage() {}

func (x *AddBinaryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBinaryDataRequest.ProtoReflect.Descriptor instead.
func (*AddBinaryDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{4}
}

func (x *AddBinaryDataRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AddBinaryDataRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type AddBinaryDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddBinaryDataResponse) Reset() {
	*x = AddBinaryDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBinaryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBinaryDataResponse) ProtoMessage() {}

func (x *AddBinaryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBinaryDataResponse.ProtoReflect.Descriptor instead.
func (*AddBinaryDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{5}
}

type AddTextDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Data   string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddTextDataRequest) Reset() {
	*x = AddTextDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTextDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTextDataRequest) ProtoMessage() {}

func (x *AddTextDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTextDataRequest.ProtoReflect.Descriptor instead.
func (*AddTextDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{6}
}

func (x *AddTextDataRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *AddTextDataRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type AddTextDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddTextDataResponse) Reset() {
	*x = AddTextDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTextDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTextDataResponse) ProtoMessage() {}

func (x *AddTextDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTextDataResponse.ProtoReflect.Descriptor instead.
func (*AddTextDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{7}
}

type GetUserDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserDataRequest) Reset() {
	*x = GetUserDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataRequest) ProtoMessage() {}

func (x *GetUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataRequest.ProtoReflect.Descriptor instead.
func (*GetUserDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{8}
}

type GetUserDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserDataResponse) Reset() {
	*x = GetUserDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataResponse) ProtoMessage() {}

func (x *GetUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataResponse.ProtoReflect.Descriptor instead.
func (*GetUserDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{9}
}

type GetUserCardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *GetUserCardRequest) Reset() {
	*x = GetUserCardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCardRequest) ProtoMessage() {}

func (x *GetUserCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCardRequest.ProtoReflect.Descriptor instead.
func (*GetUserCardRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserCardRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GetUserCardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserCards []*GetUserCardResponse_UserCard `protobuf:"bytes,1,rep,name=user_cards,json=userCards,proto3" json:"user_cards,omitempty"`
}

func (x *GetUserCardResponse) Reset() {
	*x = GetUserCardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCardResponse) ProtoMessage() {}

func (x *GetUserCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCardResponse.ProtoReflect.Descriptor instead.
func (*GetUserCardResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserCardResponse) GetUserCards() []*GetUserCardResponse_UserCard {
	if x != nil {
		return x.UserCards
	}
	return nil
}

type GetUserLoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *GetUserLoginRequest) Reset() {
	*x = GetUserLoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLoginRequest) ProtoMessage() {}

func (x *GetUserLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLoginRequest.ProtoReflect.Descriptor instead.
func (*GetUserLoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserLoginRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GetUserLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserLogins []*GetUserLoginResponse_UserLogin `protobuf:"bytes,1,rep,name=user_logins,json=userLogins,proto3" json:"user_logins,omitempty"`
}

func (x *GetUserLoginResponse) Reset() {
	*x = GetUserLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLoginResponse) ProtoMessage() {}

func (x *GetUserLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLoginResponse.ProtoReflect.Descriptor instead.
func (*GetUserLoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserLoginResponse) GetUserLogins() []*GetUserLoginResponse_UserLogin {
	if x != nil {
		return x.UserLogins
	}
	return nil
}

type GetUserTextDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *GetUserTextDataRequest) Reset() {
	*x = GetUserTextDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserTextDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTextDataRequest) ProtoMessage() {}

func (x *GetUserTextDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTextDataRequest.ProtoReflect.Descriptor instead.
func (*GetUserTextDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserTextDataRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GetUserTextDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserTextRecords []*GetUserTextDataResponse_UserTextData `protobuf:"bytes,1,rep,name=user_text_records,json=userTextRecords,proto3" json:"user_text_records,omitempty"`
}

func (x *GetUserTextDataResponse) Reset() {
	*x = GetUserTextDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserTextDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTextDataResponse) ProtoMessage() {}

func (x *GetUserTextDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTextDataResponse.ProtoReflect.Descriptor instead.
func (*GetUserTextDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserTextDataResponse) GetUserTextRecords() []*GetUserTextDataResponse_UserTextData {
	if x != nil {
		return x.UserTextRecords
	}
	return nil
}

type GetUserBinaryDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
}

func (x *GetUserBinaryDataRequest) Reset() {
	*x = GetUserBinaryDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBinaryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBinaryDataRequest) ProtoMessage() {}

func (x *GetUserBinaryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBinaryDataRequest.ProtoReflect.Descriptor instead.
func (*GetUserBinaryDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserBinaryDataRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GetUserBinaryDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserBinaryRecords []*GetUserBinaryDataResponse_UserBinaryData `protobuf:"bytes,1,rep,name=user_binary_records,json=userBinaryRecords,proto3" json:"user_binary_records,omitempty"`
}

func (x *GetUserBinaryDataResponse) Reset() {
	*x = GetUserBinaryDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBinaryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBinaryDataResponse) ProtoMessage() {}

func (x *GetUserBinaryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBinaryDataResponse.ProtoReflect.Descriptor instead.
func (*GetUserBinaryDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserBinaryDataResponse) GetUserBinaryRecords() []*GetUserBinaryDataResponse_UserBinaryData {
	if x != nil {
		return x.UserBinaryRecords
	}
	return nil
}

type GetUserCardResponse_UserCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Number string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Date   string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Code   string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetUserCardResponse_UserCard) Reset() {
	*x = GetUserCardResponse_UserCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCardResponse_UserCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCardResponse_UserCard) ProtoMessage() {}

func (x *GetUserCardResponse_UserCard) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCardResponse_UserCard.ProtoReflect.Descriptor instead.
func (*GetUserCardResponse_UserCard) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GetUserCardResponse_UserCard) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GetUserCardResponse_UserCard) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *GetUserCardResponse_UserCard) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetUserCardResponse_UserCard) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetUserLoginResponse_UserLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Login  string `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	Pwd    string `protobuf:"bytes,3,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *GetUserLoginResponse_UserLogin) Reset() {
	*x = GetUserLoginResponse_UserLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserLoginResponse_UserLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLoginResponse_UserLogin) ProtoMessage() {}

func (x *GetUserLoginResponse_UserLogin) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLoginResponse_UserLogin.ProtoReflect.Descriptor instead.
func (*GetUserLoginResponse_UserLogin) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{13, 0}
}

func (x *GetUserLoginResponse_UserLogin) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GetUserLoginResponse_UserLogin) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetUserLoginResponse_UserLogin) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type GetUserTextDataResponse_UserTextData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Data   string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetUserTextDataResponse_UserTextData) Reset() {
	*x = GetUserTextDataResponse_UserTextData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserTextDataResponse_UserTextData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTextDataResponse_UserTextData) ProtoMessage() {}

func (x *GetUserTextDataResponse_UserTextData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTextDataResponse_UserTextData.ProtoReflect.Descriptor instead.
func (*GetUserTextDataResponse_UserTextData) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{15, 0}
}

func (x *GetUserTextDataResponse_UserTextData) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GetUserTextDataResponse_UserTextData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type GetUserBinaryDataResponse_UserBinaryData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Data   string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetUserBinaryDataResponse_UserBinaryData) Reset() {
	*x = GetUserBinaryDataResponse_UserBinaryData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_keeper_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserBinaryDataResponse_UserBinaryData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBinaryDataResponse_UserBinaryData) ProtoMessage() {}

func (x *GetUserBinaryDataResponse_UserBinaryData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_keeper_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBinaryDataResponse_UserBinaryData.ProtoReflect.Descriptor instead.
func (*GetUserBinaryDataResponse_UserBinaryData) Descriptor() ([]byte, []int) {
	return file_internal_proto_keeper_proto_rawDescGZIP(), []int{17, 0}
}

func (x *GetUserBinaryDataResponse_UserBinaryData) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GetUserBinaryDataResponse_UserBinaryData) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_internal_proto_keeper_proto protoreflect.FileDescriptor

var file_internal_proto_keeper_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x11,
	0x0a, 0x0f, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x51, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x70, 0x77, 0x64, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x42, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x42,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x17, 0x0a, 0x15,
	0x41, 0x64, 0x64, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x40, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x54, 0x65, 0x78, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f,
	0x6d, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x15, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x54, 0x65,
	0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2c, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0xbd, 0x01, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x42, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72,
	0x43, 0x61, 0x72, 0x64, 0x73, 0x1a, 0x62, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2d, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0xab, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x46, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x0a, 0x75,
	0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x73, 0x1a, 0x4b, 0x0a, 0x09, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x70, 0x77, 0x64, 0x22, 0x30, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0xae, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x78,
	0x74, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54,
	0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0f, 0x75, 0x73,
	0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0x3a, 0x0a,
	0x0c, 0x55, 0x73, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x32, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x22, 0xba, 0x01,
	0x0a, 0x19, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5f, 0x0a, 0x13, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x11, 0x75, 0x73, 0x65, 0x72, 0x42,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0x3c, 0x0a, 0x0e,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x94, 0x05, 0x0a, 0x0a, 0x49,
	0x6e, 0x66, 0x6f, 0x4b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x43, 0x61, 0x72, 0x64, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12,
	0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x41, 0x64, 0x64, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4a, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x69, 0x6e,
	0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b,
	0x41, 0x64, 0x64, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x64, 0x64, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x56, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69,
	0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42,
	0x69, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4a, 0x75, 0x6c, 0x69, 0x61, 0x2d, 0x69, 0x76, 0x76, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x2d, 0x6b,
	0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x67, 0x69, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_keeper_proto_rawDescOnce sync.Once
	file_internal_proto_keeper_proto_rawDescData = file_internal_proto_keeper_proto_rawDesc
)

func file_internal_proto_keeper_proto_rawDescGZIP() []byte {
	file_internal_proto_keeper_proto_rawDescOnce.Do(func() {
		file_internal_proto_keeper_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_keeper_proto_rawDescData)
	})
	return file_internal_proto_keeper_proto_rawDescData
}

var file_internal_proto_keeper_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_internal_proto_keeper_proto_goTypes = []interface{}{
	(*AddCardRequest)(nil),                           // 0: proto.AddCardRequest
	(*AddCardResponse)(nil),                          // 1: proto.AddCardResponse
	(*AddLoginRequest)(nil),                          // 2: proto.AddLoginRequest
	(*AddLoginResponse)(nil),                         // 3: proto.AddLoginResponse
	(*AddBinaryDataRequest)(nil),                     // 4: proto.AddBinaryDataRequest
	(*AddBinaryDataResponse)(nil),                    // 5: proto.AddBinaryDataResponse
	(*AddTextDataRequest)(nil),                       // 6: proto.AddTextDataRequest
	(*AddTextDataResponse)(nil),                      // 7: proto.AddTextDataResponse
	(*GetUserDataRequest)(nil),                       // 8: proto.GetUserDataRequest
	(*GetUserDataResponse)(nil),                      // 9: proto.GetUserDataResponse
	(*GetUserCardRequest)(nil),                       // 10: proto.GetUserCardRequest
	(*GetUserCardResponse)(nil),                      // 11: proto.GetUserCardResponse
	(*GetUserLoginRequest)(nil),                      // 12: proto.GetUserLoginRequest
	(*GetUserLoginResponse)(nil),                     // 13: proto.GetUserLoginResponse
	(*GetUserTextDataRequest)(nil),                   // 14: proto.GetUserTextDataRequest
	(*GetUserTextDataResponse)(nil),                  // 15: proto.GetUserTextDataResponse
	(*GetUserBinaryDataRequest)(nil),                 // 16: proto.GetUserBinaryDataRequest
	(*GetUserBinaryDataResponse)(nil),                // 17: proto.GetUserBinaryDataResponse
	(*GetUserCardResponse_UserCard)(nil),             // 18: proto.GetUserCardResponse.UserCard
	(*GetUserLoginResponse_UserLogin)(nil),           // 19: proto.GetUserLoginResponse.UserLogin
	(*GetUserTextDataResponse_UserTextData)(nil),     // 20: proto.GetUserTextDataResponse.UserTextData
	(*GetUserBinaryDataResponse_UserBinaryData)(nil), // 21: proto.GetUserBinaryDataResponse.UserBinaryData
}
var file_internal_proto_keeper_proto_depIdxs = []int32{
	18, // 0: proto.GetUserCardResponse.user_cards:type_name -> proto.GetUserCardResponse.UserCard
	19, // 1: proto.GetUserLoginResponse.user_logins:type_name -> proto.GetUserLoginResponse.UserLogin
	20, // 2: proto.GetUserTextDataResponse.user_text_records:type_name -> proto.GetUserTextDataResponse.UserTextData
	21, // 3: proto.GetUserBinaryDataResponse.user_binary_records:type_name -> proto.GetUserBinaryDataResponse.UserBinaryData
	0,  // 4: proto.InfoKeeper.AddCard:input_type -> proto.AddCardRequest
	2,  // 5: proto.InfoKeeper.AddLogin:input_type -> proto.AddLoginRequest
	4,  // 6: proto.InfoKeeper.AddBinaryData:input_type -> proto.AddBinaryDataRequest
	6,  // 7: proto.InfoKeeper.AddTextData:input_type -> proto.AddTextDataRequest
	8,  // 8: proto.InfoKeeper.GetUserData:input_type -> proto.GetUserDataRequest
	10, // 9: proto.InfoKeeper.GetUserCard:input_type -> proto.GetUserCardRequest
	12, // 10: proto.InfoKeeper.GetUserLogin:input_type -> proto.GetUserLoginRequest
	14, // 11: proto.InfoKeeper.GetUserTextData:input_type -> proto.GetUserTextDataRequest
	16, // 12: proto.InfoKeeper.GetUserBinaryData:input_type -> proto.GetUserBinaryDataRequest
	1,  // 13: proto.InfoKeeper.AddCard:output_type -> proto.AddCardResponse
	3,  // 14: proto.InfoKeeper.AddLogin:output_type -> proto.AddLoginResponse
	5,  // 15: proto.InfoKeeper.AddBinaryData:output_type -> proto.AddBinaryDataResponse
	7,  // 16: proto.InfoKeeper.AddTextData:output_type -> proto.AddTextDataResponse
	9,  // 17: proto.InfoKeeper.GetUserData:output_type -> proto.GetUserDataResponse
	11, // 18: proto.InfoKeeper.GetUserCard:output_type -> proto.GetUserCardResponse
	13, // 19: proto.InfoKeeper.GetUserLogin:output_type -> proto.GetUserLoginResponse
	15, // 20: proto.InfoKeeper.GetUserTextData:output_type -> proto.GetUserTextDataResponse
	17, // 21: proto.InfoKeeper.GetUserBinaryData:output_type -> proto.GetUserBinaryDataResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_proto_keeper_proto_init() }
func file_internal_proto_keeper_proto_init() {
	if File_internal_proto_keeper_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_keeper_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBinaryDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBinaryDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTextDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTextDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserLoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserTextDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserTextDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBinaryDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBinaryDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCardResponse_UserCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserLoginResponse_UserLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserTextDataResponse_UserTextData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_keeper_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserBinaryDataResponse_UserBinaryData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_keeper_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_keeper_proto_goTypes,
		DependencyIndexes: file_internal_proto_keeper_proto_depIdxs,
		MessageInfos:      file_internal_proto_keeper_proto_msgTypes,
	}.Build()
	File_internal_proto_keeper_proto = out.File
	file_internal_proto_keeper_proto_rawDesc = nil
	file_internal_proto_keeper_proto_goTypes = nil
	file_internal_proto_keeper_proto_depIdxs = nil
}
