// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: user_binary_record.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserBinaryRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt    []byte `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Note      []byte `protobuf:"bytes,3,opt,name=note,proto3" json:"note,omitempty"`
	TimeStamp string `protobuf:"bytes,4,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
}

func (x *UserBinaryRecord) Reset() {
	*x = UserBinaryRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_binary_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserBinaryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBinaryRecord) ProtoMessage() {}

func (x *UserBinaryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_user_binary_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBinaryRecord.ProtoReflect.Descriptor instead.
func (*UserBinaryRecord) Descriptor() ([]byte, []int) {
	return file_user_binary_record_proto_rawDescGZIP(), []int{0}
}

func (x *UserBinaryRecord) GetPrompt() []byte {
	if x != nil {
		return x.Prompt
	}
	return nil
}

func (x *UserBinaryRecord) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UserBinaryRecord) GetNote() []byte {
	if x != nil {
		return x.Note
	}
	return nil
}

func (x *UserBinaryRecord) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

var File_user_binary_record_proto protoreflect.FileDescriptor

var file_user_binary_record_proto_rawDesc = []byte{
	0x0a, 0x18, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x62, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x5f, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x71, 0x0a, 0x10, 0x55, 0x73, 0x65, 0x72, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53,
	0x74, 0x61, 0x6d, 0x70, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x4a, 0x75, 0x6c, 0x69, 0x61, 0x2d, 0x69, 0x76, 0x76, 0x2f, 0x69, 0x6e, 0x66,
	0x6f, 0x2d, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x67, 0x69, 0x74, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_user_binary_record_proto_rawDescOnce sync.Once
	file_user_binary_record_proto_rawDescData = file_user_binary_record_proto_rawDesc
)

func file_user_binary_record_proto_rawDescGZIP() []byte {
	file_user_binary_record_proto_rawDescOnce.Do(func() {
		file_user_binary_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_binary_record_proto_rawDescData)
	})
	return file_user_binary_record_proto_rawDescData
}

var file_user_binary_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_binary_record_proto_goTypes = []interface{}{
	(*UserBinaryRecord)(nil), // 0: proto.UserBinaryRecord
}
var file_user_binary_record_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_binary_record_proto_init() }
func file_user_binary_record_proto_init() {
	if File_user_binary_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_binary_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserBinaryRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_binary_record_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_binary_record_proto_goTypes,
		DependencyIndexes: file_user_binary_record_proto_depIdxs,
		MessageInfos:      file_user_binary_record_proto_msgTypes,
	}.Build()
	File_user_binary_record_proto = out.File
	file_user_binary_record_proto_rawDesc = nil
	file_user_binary_record_proto_goTypes = nil
	file_user_binary_record_proto_depIdxs = nil
}
