// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: user_card.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prompt    string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Number    string `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Date      string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Code      string `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Note      string `protobuf:"bytes,5,opt,name=note,proto3" json:"note,omitempty"`
	TimeStamp string `protobuf:"bytes,6,opt,name=time_stamp,json=timeStamp,proto3" json:"time_stamp,omitempty"`
}

func (x *UserCard) Reset() {
	*x = UserCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_card_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCard) ProtoMessage() {}

func (x *UserCard) ProtoReflect() protoreflect.Message {
	mi := &file_user_card_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCard.ProtoReflect.Descriptor instead.
func (*UserCard) Descriptor() ([]byte, []int) {
	return file_user_card_proto_rawDescGZIP(), []int{0}
}

func (x *UserCard) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *UserCard) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *UserCard) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *UserCard) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserCard) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *UserCard) GetTimeStamp() string {
	if x != nil {
		return x.TimeStamp
	}
	return ""
}

var File_user_card_proto protoreflect.FileDescriptor

var file_user_card_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x95, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65,
	0x72, 0x43, 0x61, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x6d, 0x70, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x6d, 0x70,
	0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a,
	0x75, 0x6c, 0x69, 0x61, 0x2d, 0x69, 0x76, 0x76, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x2d, 0x6b, 0x65,
	0x65, 0x70, 0x65, 0x72, 0x2e, 0x67, 0x69, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_card_proto_rawDescOnce sync.Once
	file_user_card_proto_rawDescData = file_user_card_proto_rawDesc
)

func file_user_card_proto_rawDescGZIP() []byte {
	file_user_card_proto_rawDescOnce.Do(func() {
		file_user_card_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_card_proto_rawDescData)
	})
	return file_user_card_proto_rawDescData
}

var file_user_card_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_card_proto_goTypes = []interface{}{
	(*UserCard)(nil), // 0: proto.UserCard
}
var file_user_card_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_card_proto_init() }
func file_user_card_proto_init() {
	if File_user_card_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_card_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_card_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_card_proto_goTypes,
		DependencyIndexes: file_user_card_proto_depIdxs,
		MessageInfos:      file_user_card_proto_msgTypes,
	}.Build()
	File_user_card_proto = out.File
	file_user_card_proto_rawDesc = nil
	file_user_card_proto_goTypes = nil
	file_user_card_proto_depIdxs = nil
}
